### ISSUE TITLE
If there're files renamed and staged, invalid files are "open"ed by the action

### ISSUE THREAD

**Issue by kyoh86** [kuuote/ddu-source-git_status#1]
## How to reproduce?

1. Do `git rename`

```console
$ git rename foo bar
```

2. Open ddu with the source `git_status`
3. Call the "open" item action.

## What'll be happend?

"foo => bar" will be opened.

## What I expect

"bar" is opened.

**Comment by kyoh86** [comment]
mistake: 

~"foo => bar" will be opened.~ 
"foo -> bar" will be opened.

**Comment by kuuote** [comment]
@kyoh86 Could you try #2?

**Comment by kyoh86** [comment]
@kuuote thanks, it will fix!
