### ISSUE TITLE
git mvした後に表示される選択肢がおかしい

### ISSUE THREAD

**Issue by kyoh86** [kuuote/ddu-source-git_status#5]
`git mv` でファイルを移動させると、その後でddu-source-git_statusを使用すると表示がくずれて、そのitemはopenできないようです。
![image](https://github.com/kuuote/ddu-source-git_status/assets/5582459/6658af13-5b2f-4412-82a3-2ab8771472dd)

**Comment by kuuote** [comment]
#4 頂いていたのでマージしました、すみません。
